### PR TITLE
emacspeak-chess: fix spelling

### PR DESCRIPTION
**Pull request by hendursaga**
First contribution!

### CODE REVIEW

**Comment by tvraman** [comment]
Unclear what "spelling errors" you're trying to fix, 

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by hendursaga** [comment]
s/FITNCHESS/FITNESS/ is the most important spelling mistake, being in the license, and then there's s/axies/axes/, s/to/do/, and then some minor formatting changes while I'm at it. I did realize, after looking through a # of other files, that "sCoord" is intentional, I could revert that and squash if you want?

**Comment by tvraman** [comment]
Thanks. will take a look.

In general for typos etc, a simple line number and a replacement pattern
is easier for me to handle than a PR/diff since it's much harder to tell
with those as to what is being changed. Also, never include formatting
changes in such a PR.
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by hendursaga** [comment]
> never include formatting changes in such a PR.

Pardon, when I say "formatting changes" I don't mean, say, changing the structure of a s-exp, but rather, in this case, at line 51, char 48, there's two extra spaces between words, or earlier in 51:3, where the @item has an extra space before it, unlike the others..

**Comment by tvraman** [comment]
I'll take care of it. diff is too heavy weight a hammer for this, and in
general, never include whitespace changes in a patch.


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Pull request closed without merging**
