### PR TITLE
Add mac-espeak server to be used on mac OS.

### PR DESCRIPTION
**Pull request by ragb**
Reuses linux-espeak, only different Makefile and flags.

### CODE REVIEW

**Comment by tvraman** [comment]
Thanks for getting this started.

However, introducing a mac-espeak directory purely for this build makes
it a bit ugly --- can you rework it to avoid a separate directory? Also,
what is the motivation for building espeak on the Mac in the first
place, Mac has its  TTS engine -- and as it is Mac lusers complain about
"emacspeak being hard to install", so I really am not supportive of
introducing the additional Mac complication.

Another possibility might be for you to build this as a  small Mac
add-on and see if users bother with it.
-- 

--

**Comment by ragb** [comment]
Hi,

Motivation is really to have speak work on emacs for Mac OS, instead of Mac OS’s TTS engine. For programming I found it much more productive. Don’t use wit VoiceOver because it’s simply not possible, yet. Someone need to create a bridge from Mac OS Speech ApI to speak-ng.

I’ll try reworking this to avoid different directories, or create an external repo to keep it, which ever you believe it’s easier.

Regarding Espeak (and espeak-ng) being hard to install on Mac OS I can kinda relate, however
 As these days it’s all autotools-based stuff I believe any emacspeak user would be able to install it from source, or from an hhomebrew tap which is easily provisioned.

**Comment by ragb** [comment]
Just changed Makefile to build both for Mac and Linux. Probably linux-speak directory name is now a bit inconsistent...

**Comment by tvraman** [comment]
is it in the original 32.patch?
Yes , see my earlier response, we can eventually rename linux-espeak to
mac-espeak in a separate cl.
--

**Comment by ragb** [comment]
No, just committed with that change. Actually simplifies the code of espeak TCL program also.

**Comment by ragb** [comment]
I’m using it daily: emacspeak with espeak on Mac OS.

I believe the emacspeak installation is not easy for all users, don’t know any other method 
Than running from source. I might be able to create an homebrew package for emacspeak like I did for espeak-ng and pcaudioli (espeak-mg dependency) to make things easier for people.

**Comment by tvraman** [comment]
All checked in. Thanks for the patch.
--

**Comment by tvraman** [comment]
Running emacspeak from source is much easier than any prepackaged
solution. When I first saw your patch I was thinking of just having the
espeak server packaged separately, not needed now since the patch is
checked in.


--

**Comment by ragb** [comment]
You missed a rename in the top-level Makefile when building espeak server. Not a big deal though.

**Comment by tvraman** [comment]
Closed: merged

**Pull request closed without merging**
