### PR TITLE
Espeak voice selection support + other fixes

### PR DESCRIPTION
**Pull request by krzysz00**
This is the draft of the work I've been doing on the espeak voice selection support.

The basic setup (being able to switch variants) works just fine, but
1. I'm not convinced I've picked a good way to expose the functionality to users and,
2. There's crashes shortly after switching to MBROLA voices in particular. Since I could switch to those voices fine during testing, I'm suspecting something to do either with cancelling output or with `tts_sync_state`

While I don't quite think this is ready to merge, I'd like to get the code review going in parallel with debugging.

(And while it'd be quite nice to have a voice selection menu, I'm leaving that to future work)

### CODE REVIEW

**Comment by tvraman** [comment]
1. Please merge your earlier pitch adjustment PR in to this one so we
   can handle them all together.
   
   2. When ready, we wont do a Menu of voices --- menus are for
      WIMPs:-) -- we'll do completion.

**Comment by tvraman** [comment]
So my first suggestion would be to fold voice variant into the
language for espeak rather than having a separate  (optional voice
name) argument in set language calls. This would both avoid
over-engineering things and match up with how espeak names its voices
eg mbrola-en-us-1 or whatever

**Comment by krzysz00** [comment]
1. The pitch adjustment PR is already on master and is thus incorporated here
2. Hm ... that suggestion mostly makes sense, since if, for example, someone calls for `en-us+whisper` on the command line, espeak will already do the right thing when it comes to setting the variant and language. The tricky thing becomes when we can't autodetect, like with mb-en1, which might be a voice for en-gb or en-us or so on. So for the ambiguous ones, I'd argue for extending the syntax to something like `en-gb:mb-en1` that we can then pick apart in the server.

**Comment by tvraman** [comment]
Krzysztof Drewniak ***@***.***> writes:

SG re a simple syntax extension that we can parse out in  the
speechserver.

Had forgotten that I had already merged the pitch change -- as you can
tell, this is not something I work on fulltime in any sense.

> 1 The pitch adjustment PR is already on master and is thus
>   incorporated here
> 2 Hm ... that suggestion mostly makes sense, since if, for example,
>   someone calls for en-us+whisper on the command line, espeak will
>   already do the right thing when it comes to setting the variant and
>   language. The tricky thing becomes when we can't autodetect, like
>   with mb-en1, which might be a voice for en-gb or en-us or so on. So
>   for the ambiguous ones, I'd argue for extending the syntax to
>   something like en-gb:mb-en1 that we can then pick apart in the
>   server.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you commented.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
In an interesting note, it looks like getting a list of voice variants involves, in effect, calls to `ls` (going off how NVDA does it). I'll need to consider how to handle this ... hardcoding the list could work ...

**Comment by tvraman** [comment]
Using ls is fine -- see how emacspeak handles amixer for similar
requirements.


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
Good news, it turns out there was an API that got me the directory path I wanted, though it was not named very well.

And so I now have what I'd consider a solid initial draft of the voice selection system working. I've tested basic functionality from within emacs, and done a slightly more extensive test from the command line as follows

```
$ ./servers/espeak
%echo $voicename(current)
gmw/en-US
%say Iwona
%set_lang pl
%say Iwona 
%echo $voicename(current)
zlw/pl
%set_lang :whisper
%say Iwona
%set_lang en-us:whisper
%say Iwona
%echo $voicename(current)
en-us+whisper
%set_lang pl
%say Iwona
```
where the first four calls to `say` are meant to come out different, and the last one should be the whispered Polish version (`say` \#3)

There's still a deadlock involving mbrola voices, and I'll be taking some time to work out if it's an espeak bug. The reproducer is something like
```
%set_lang :mb-en1
%say {some words}
%say some words
```
which'll cut off after the second "some"

**Comment by tvraman** [comment]
thx, will  take a look in the next few days.

In the meantime use it for a couple of weeks as a pretest before we
think of merging it into the main branch.

Note: I'll release the next public Emacspeak sometime in early May, so
if we want to target that release, we should have merged it in by
Apr 15.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
So where did you get the ivona voices for espeak?

I get an error (lang 88) which makes me suspect I dont have those
voices around in espeak.
set_lang pl gives an error in my environment.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
also I often  get an number of voices exceeded error in espeak after
updates, and it appears because of a duplicated directory in
espeak-data/voices -- have you seen this?
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
Huh, the thing with lang 88 is interesting - I'm hoping I don't have a bug in the tcl part somewhere

Iwona was a test string - a polish name, specifically

I haven't seen the number of voices exceeded error, but I can see it being the result of duplicate files - espeak probably makes assumptions about the voice directory it ships with.

**Comment by krzysz00** [comment]
My current thoughts are to mark that MBROLA voices may not work and ship this anyway

**Comment by tvraman** [comment]
Krzysztof Drewniak ***@***.***> writes:


That'll likely turn out to be hasty and just generate questions that we
wont have the cycles to answer.

As a first step, create an espeak-todo.org file in the native-espeak
directory with:

1. Current state of what works
2. What remains to be done.
3. What user-visible improvements this current update delivers.

From experience, we never receive much by the way of thanks for
releasing things but a lot of bricks when something even fails
marginally --- that also includes failures due to luser error.


 > My current thoughts are to mark that MBROLA voices may not work and
> ship this anyway
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
I've updated the todo file and, probably more usefully, edited the server to reject attempts to switch to MBROLA voices for now.

**Comment by tvraman** [comment]
1. Please rebase your branch on the latest master and push in
   preparation for merging.
2. You need to update the todo per original message -- specifically it
   needs to document what user visible changes this introduces.

Let me know when those are done.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
1. Merge conflict fixed, thanks for pointing out I had one
2. I hope the "Changes in Emacspeak 56" section I've added is sufficient

**Comment by tvraman** [comment]
Plese do not add things directly into the News file that presupposes
it's part of this release.

Next, I need you to test the language switching with the outloud server
to make sure nothing there breaks due to your changes in dtk-speak.el

Also, confirm that the code compiles with no warnings -- both elisp and
C

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
the update-espeak is messed up -- and I dont have time to fight this
with git.

Here is what it says:

git checkout update-espeak
Switched to branch 'update-espeak'
Your branch and 'master' have diverged,
and have 5 and 34 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
07:04:35 raman-glaptop emacspeak $ git pull
From .
 * branch                master     -> FETCH_HEAD
fatal: Not possible to fast-forward, aborting.
07:04:39 raman-glaptop emacspeak $ 
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
blew away old branch and pull the PR again all is well at my end; so
ignore earlier message re git being confused.

Good job on the readme, will review and run over the next few days.

**Comment by tvraman** [comment]
Sadly the espeak server with these updates blows up like so:

make
g++ -g    -O2 -fPIC  -DPIC  -pedantic -ansi -Wall -Wno-long-long --std=c++11 -I/usr/include/tcl8.6   -c -o tclespeak.o tclespeak.cpp
g++  -shared -o tclespeak.so tclespeak.o -ltcl8.6 -lespeak-ng
13:07:21 raman-glaptop native-espeak $ cd ..
13:07:26 raman-glaptop servers $ ./espeak
Using SoX
no files matched glob pattern "*"
    while executing
"glob -tails -directory [ttsDataPath]/voices/!v *"
    invoked from within
"foreach variant [glob -tails -directory [ttsDataPath]/voices/!v *] {
    set voiceVariants($variant) {}
}"
    (file "./espeak" line 525)
13:07:29 raman-glaptop servers $

**Comment by krzysz00** [comment]
Very strange

I'll admit to being initially confused by the SoX message - I don't have that.

Could I get an `ls [...]/espeak-ng-data/voices/` from that machine? `[...]` is /usr/lib/x86_64-linux-gnu/` in the Ubuntu package.

I think there may be something non-standard or broken about your espeak-ng installation

**Comment by krzysz00** [comment]
In further comments:
1. Sorry about the issue with the branch - you'd said to rebase and so I thought you were expecting me to force-push a rebased version of my branch. I hope it wasn't too much bother.
2. Re outloud: the only change I've made to dtk-speak.el is in the documentation. From looking at the outloud server, attempts to use the voice selection syntax will get kicked back with a "language not found" error.
3. I've pushed a commit that, unless I've messed up, will allow espeak to start even if the voices directory is in unexpected state (I didn't realize that TCL globs threw an error when nothing matched by default). Said change should also give us your value of `ttsDataPath`

**Comment by tvraman** [comment]
Krzysztof Drewniak ***@***.***> writes:


quite possible, though the current espeak server works fine, 
I'm getting tcl errors from your update.
> Very strange
>
> I'll admit to being initially confused by the SoX message - I don't
> have that.
>
> Could I get an ls [...]/espeak-ng-data/voices/ from that machine?
> [...] is /usr/lib/x86_64-linux-gnu/` in the Ubuntu package.

eSpeak NG text-to-speech: 1.50  Data at:
/usr/lib/x86_64-linux-gnu/espeak-ng-data
ls    -1 /usr/lib/x86_64-linux-gnu/espeak-ng-data
af_dict
am_dict
an_dict
ar_dict
as_dict
az_dict
ba_dict
bg_dict
bn_dict
bpy_dict
bs_dict
ca_dict
cs_dict
cy_dict
da_dict
de_dict
el_dict
en_dict
eo_dict
es_dict
et_dict
eu_dict
fa_dict
fi_dict
fr_dict
ga_dict
gd_dict
gn_dict
grc_dict
gu_dict
hak_dict
hi_dict
hr_dict
ht_dict
hu_dict
hy_dict
ia_dict
id_dict
intonations
is_dict
it_dict
ja_dict
jbo_dict
ka_dict
kk_dict
kl_dict
kn_dict
ko_dict
kok_dict
ku_dict
ky_dict
la_dict
lang/
lfn_dict
lt_dict
lv_dict
mbrola_ph/
mi_dict
mk_dict
ml_dict
mr_dict
ms_dict
mt_dict
my_dict
nci_dict
ne_dict
nl_dict
no_dict
om_dict
or_dict
pa_dict
pap_dict
phondata
phondata-manifest
phonindex
phontab
pl_dict
pt_dict
py_dict
quc_dict
ro_dict
ru_dict
sd_dict
shn_dict
si_dict
sk_dict
sl_dict
sq_dict
sr_dict
sv_dict
sw_dict
ta_dict
te_dict
tn_dict
tr_dict
tt_dict
ur_dict
uz_dict
vi_dict
voices/
zh_dict
zhy_dict
18:55:25 raman-glaptop ~ $ 

>
> I think there may be something non-standard or broken about your
> espeak-ng installation
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
Krzysztof Drewniak ***@***.***> writes:


I've lost touch with the espeak server implement; where does ttsDataPath
 come from -- grep doesn't find it in  master branch.
> In further comments:
>
> 1 Sorry about the issue with the branch - you'd said to rebase and so
>   I thought you were expecting me to force-push a rebased version of
>   my branch. I hope it wasn't too much bother.
> 2 Re outloud: the only change I've made to dtk-speak.el is in the
>   documentation. From looking at the outloud server, attempts to use
>   the voice selection syntax will get kicked back with a "language not
>   found" error.
> 3 I've pushed a commit that, unless I've messed up, will allow espeak
>   to start even if the voices directory is in unexpected state (I
>   didn't realize that TCL globs threw an error when nothing matched by
>   default). Said change should also give us your value of ttsDataPath
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
`ttsDataPath` is new - see https://github.com/tvraman/emacspeak/pull/64/files#diff-59bb2b4eca4916a4d8cacd76ba97145a4804479657c66fb0bb6d638b187edf3eR358  (line 358 of `tclespeak.cpp` in my branch) for the details. It uses `espeak_Info()` to get the path to espeak's data directory.

I've fixed the espeak server to still run if `[ttsDataPath]/voices/!v` is non-existent - so now calling `ttsDataPath` from the espeak server REPL should tell us where espeak is looking for its voices.

**Comment by tvraman** [comment]
The latest pull works -- a few comments:
C-e D N and C-e d P with espeak dont appear to announce the name of
the  voice/lang it switched to --- it should.

2. I did a quick test for English and :victor and :whisper worked -- 

3. Also, would you like to volunteer to be the primary maintainer of
   the espeak server? Nothing  too formal other than that I'd list you
   as the maintainer in the server code and  would leave you the
    job of replying on the mailing list based on your availability.

**Comment by tvraman** [comment]
And now I remember -- in my espeak install, having that !v
directory caused espeak to blow up with the error saying "too many
voices" or some such so I blew away that dir:-)



-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
The diffs to outloud and tts-lib.tcl in the servers directory look
like noise, please fix

**Comment by krzysz00** [comment]
I'll take a look at C-e d N and P tomorrow and see what the ptoblem was 

The outooud change isn't noise - this branch also fixes auditory icons in environments without aplay by moving where the -q option is specified (paplay has no -q)

And sure, I'll be the maintainer of the Espeak server!

**Comment by tvraman** [comment]
thanks.
in the future please summarize changes so that small but important
tweaks like the paplay option dont get missed.

Also paplay is going away from what I understand; pulse is being
replaced by pipewire going forward on Linux 
but I think distros will take time to catch up 


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
Thanks for testing `C-e d N` - turns out there's a different between $voicename(currrent)` and `$voicename(current)` 

The announcement of the voice (which'll include some indication of the language) being switched to is working again.

**Comment by krzysz00** [comment]
There anything else you want tested? (I've fixed the merge conflicts)

**Comment by tvraman** [comment]
I'll pull and test today and likely merge unless I discover something
new. Thanks for all your hard work, this is now close to the finish-line
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
Merged  into master on April 21, 2022.

**Comment by tvraman** [comment]
I updated my espeak and the error from last night went away. However I
still dont get any ivona voices -- assuming this ivona is the same
that I know from Android from about 10 years ago -- that was a Polish
TTS company that Amazon Acquired.

Attaching the log of my run below.

Using SoX
%echo $voicename(current)
en-us
%set_lang pl
%say Iwona 
%echo $voicename(current)
pl
%set_lang :whisper
%say whisper
%say whisper
%say testing 
%set_lang en-us:whisper
%say "this is a test"
%set_lang en-us:whisper
%echo $voicename(current)
pl
%
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
I updated my espeak and the error from last night went away. However I
still dont get any ivona voices -- assuming this ivona is the same
that I know from Android from about 10 years ago -- that was a Polish
TTS company that Amazon Acquired.

Attaching the log of my run below.

Using SoX
%echo $voicename(current)
en-us
%set_lang pl
%say Iwona 
%echo $voicename(current)
pl
%set_lang :whisper
%say whisper
%say whisper
%say testing 
%set_lang en-us:whisper
%say "this is a test"
%set_lang en-us:whisper
%echo $voicename(current)
pl
%
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♉ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
(I was using "iwona" as a test string that has different pronunciation between English and Polish - is there a bug I should be looking in to here?)

**Comment by tvraman** [comment]
not sure what you're asking, but if I try to read between the lines,
emacspeak's pronunciation dictionaries are not language specific at
present -- so it's not a bug, it's a large unimplemented feature.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
[AMD Official Use Only - General]

To rephrase: there isn’t a “iwona” voice.

I was using the string “iwona” is one of the inputs to the espeak server while testing language switching, because how the espeak system itself pronounces the string “ivona” depends on whether espeak has been set to English or Polish.

**Pull request merged**
