### PR TITLE
Apply 2to3 to servers/mac

### PR DESCRIPTION
**Pull request by robertmeta**
This PR simply applies the python 2to3 conversion script.  It updates the env to point to python3 and it does some gentle formatting and paren cleanup for python3. 

closes: #68

(Technically, 68 was closed as of April, but I think invoking python3 is more the "right thing" and it was still open).

### CODE REVIEW

**Comment by robertmeta** [comment]
This additionally has "black" reformatting, if you would like a more straightforward just 2to3 -w application let me know.

**Comment by tvraman** [comment]
Thanks for the patch. I'd like more users to test this across different
mac installations.


I'll leave it to Mac users to apply this patch and live with it for a
while before I do anything else.
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
Let's leave the py formatting out of the patch; like I just said,  let
other Mac users test and live with the patch for a while, and we can
revisit it in a few weeks, get the actual fix in, then separately do the
formatting cleanup 
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by robertmeta** [comment]
Will create a new cleaner patch.  So going to close this and reapply a new one.  Additionally, I have tested it on modern macs (intel and m1) with both brew installed python and using the default python installer.

**Pull request closed without merging**
