### PR TITLE
Simplify puretone

### PR DESCRIPTION
**Pull request by robertmeta**
Of course after I mainline the project, I wake up witha  way better way to handle the tone generation that is simpler and cleaner and gets rid of an entire async queue.

Also improved the Makefile to update the swiftmac binary in servers directory if out of date or missing. 

@tvraman let me know if you want me to hold up and bundle rather than spam you with small PRs.

### CODE REVIEW

**Comment by tvraman** [comment]
Base the decision on how many folks you have using the update, rather
than the question you asked.


--

**Comment by robertmeta** [comment]
With that in mind, merge this then likely the flow will slow.  Thanks again!

**Comment by tvraman** [comment]
cant parse what you're trying to say
I just gather you'll work locally for a while and submit.

In general:

1. I dont plan to carefully review code in the swiftmac branch.
2. Consequently, I'll merge your patches fairly quickly, as long as
   they dont touch anything outside the swiftmac tree.
3.  It's  therefore important for you to flag any pull-request  that
   touches files outside swiftmac

   
--

**Comment by robertmeta** [comment]
Thanks, I will try to keep the vast majority of changes to bug fixes in the swiftmac subtree.

**Pull request merged**
