### PR TITLE
Add dtk-set-variant command to allow espeak's variants to be selected

### PR DESCRIPTION
**Pull request by krzysz00**
dtk-set-variant is bound to C-e d M-v.

(In addition, fix indentation in servers/espeak and fix close_tags in
tclsespeak.cpp to be more memory efficient).

### CODE REVIEW

**Comment by tvraman** [comment]
And what would the "set espeak variant" do for other synthesizers?

If only espeak specific, it belongs in espeak.el  and not in
dtk-speak.el

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
Good point, I can revise

(I have no idea if other speech synthesizers have a concept of voice variants that they expose - I haven't really done the research on this. If they do, this might make a good interface to them.)

**Comment by tvraman** [comment]
Krzysztof Drewniak ***@***.***> writes:


Perhaps extend the tts_set_language call in the espeak server to handle
variants, this way we dont introduce an additional API that every other
server has to implement, and not have to worry about variants in other
engines.

Voice variants in espeak are effectively new voices/languages --- and
having that would be nice in that you could then easily switch to the
mbrola voices etc.

If you go this route, make sure to validate by installing some mbrola
voices --
> Good point, I can revise
>
> (I have no idea if other speech synthesizers have a concept of voice
> variants that they expose - I haven't really done the research on
> this. If they do, this might make a good interface to them.)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
The main downside I can see to extending `tts_set_language` is the discoverability problem of "set language" also being "select voice", although this can be mitigated by having two user-facing commands that map to the same API.

**Comment by tvraman** [comment]
Krzysztof Drewniak ***@***.***> writes:

I dont think it's much of a discovery problem since as you say, the user
facing commands can call the API appropriately, and anyone using the API
is expected to read the documentation.
> The main downside I can see to extending tts_set_language is the
> discoverability problem of "set language" also being "select voice",
> although this can be mitigated by having two user-facing commands that
> map to the same API.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
Having looked around the code, there is an espeak-voices.el, though I haven't yet worked out where that code can be called from and how it might interact with changes to the driver.

I'll try and untangle that when I have some time (yay for day jobs and holidays) and will submit a new PR once I've worked things out.

Thanks for the feedback!

**Comment by tvraman** [comment]
OK.

espeak-voices.el is what I meant when I said espeak.el.

It's loaded when emacspeak starts and the engine in use is espeak -- so
that's the right place to add it.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by krzysz00** [comment]
I do have a design question here, since I'm now rather confused by how responsibility is shared between [driver]-voices.el and the driver.

These files define mappings from the generic ACSS voices to driver-specific command codeh. However, they also (at least in the case of espeak and, by the looks of it, outlound) hardcode a particular voice variant, which both leads to sending the synthesizer potentially-redundant "select voice" commands and can make the values for pitch, richness, and so on conflict with other voices. On the other hand, this approach makes the synthesizer more configurable from lisp. But, on the third hand, it makes defining new voices more difficult.

There also doesn't seem to be any user-facing machinery allowing for changing the default voice short of working out which chunk of code to put in one's `.emacs`.

Having poked around espeak, tags like `<prosody>` can take percentages or relative values instead of absolute values. So, my thoughts are to remove a lot of the "paul" specific machinery and to instead keep `espeak-voices.el` generic over which voice has been selected. Then, the task of selecting the default voice could be moved into the driver, at least for `espeak`.

From a user-facing perspective, there would be an `espeak-set-default-voice` (that either goes through `set_lang`, or, more cleanly, through a separate TCL call) which might, in the future, be extended to a more general `tts-set-default-voice` if the people maintaining those bits are willing to do that.

I realize this is somewhat rambling, but does it seem reasonable overall?

**Comment by tvraman** [comment]
Krzysztof Drewniak ***@***.***> writes:

This sounds like a reasonable approach to try for espeak.

Go one step at a time, and remove the generic "paul" bits from espeak
and let's see how it works out.

Be prepared to write some throw away code but the only way to figure
these out is to write it, live with it for a few weeks and see how it
feels.

> I do have a design question here, since I'm now rather confused by how
> responsibility is shared between [driver]-voices.el and the driver.
>
> These files define mappings from the generic ACSS voices to
> driver-specific command codeh. However, they also (at least in the
> case of espeak and, by the looks of it, outlound) hardcode a
> particular voice variant, which both leads to sending the synthesizer
> potentially-redundant "select voice" commands and can make the values
> for pitch, richness, and so on conflict with other voices. On the
> other hand, this approach makes the synthesizer more configurable from
> lisp. But, on the third hand, it makes defining new voices more
> difficult.
>
> There also doesn't seem to be any user-facing machinery allowing for
> changing the default voice short of working out which chunk of code to
> put in one's .emacs.
>
> Having poked around espeak, tags like <prosody> can take percentages
> or relative values instead of absolute values. So, my thoughts are to
> remove a lot of the "paul" specific machinery and to instead keep
> espeak-voices.el generic over which voice has been selected. Then, the
> task of selecting the default voice could be moved into the driver, at
> least for espeak.
>
> From a user-facing perspective, there would be an
> espeak-set-default-voice (that either goes through set_lang, or, more
> cleanly, through a separate TCL call) which might, in the future, be
> extended to a more general tts-set-default-voice if the people
> maintaining those bits are willing to do that.
>
> I realize this is somewhat rambling, but does it seem reasonable
> overall?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Pull request closed without merging**
