### PR TITLE
Minor and subjective: make function more idiomatic / lispy

### PR DESCRIPTION
**Pull request by Boruch-Baum**
The commit message 'squash this' was because I thought one could rebase from the github interface.

### CODE REVIEW

**Comment by tvraman** [comment]
for the record, I decided to use the forked version that contains the
corssword-self-insert command, rather than the advice with the
keyboard-quit.

-- 

Thanks,

--Raman
♈ Id: kg:/m/0285kf1  🦮

**Comment by Boruch-Baum** [comment]
On 2021-01-25 17:33, T. V. Raman wrote:
>    for the record, I decided to use the forked version that contains the
>    corssword-self-insert command, rather than the advice with the
>    keyboard-quit.

No hard feelings at all. I do have a solution in testing, that uses a
simplified form of your solution, thus eliminating the need for
keyboard-quit. Unfortunately, it doesn't eliminate the occasional screen
flicker, which is something I was hoping it would also do.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by tvraman** [comment]
will continue to watch your version as well since you have it on melpa.
I'm speech-enabling crossword.el for emacspeak as and when I find some
spare time, I've always done crosswords with someone else like my
brother or my wife --- building an eyes-free interface to crossword with
respect to the type of feedback you want to generate is an interesting
problem.



-- 

Thanks,

--Raman
♈ Id: kg:/m/0285kf1  🦮

**Comment by Boruch-Baum** [comment]
On 2021-01-25 18:44, T. V. Raman wrote:
>    will continue to watch your version as well since you have it on melpa.

The testing looks good, so I'm expecting to push the commit to github as
soon as I finish the documentation.

Also, in my testing I'm seeing that the flicker problem doesn't exist in
emacs28snapshot, only emacs 26. Do you have a screen flicker when using
crossword in emacs 27?

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by tvraman** [comment]
:-) re screen flicker -- I cant see the screen at all, so it definitely
doesn't flicker for me;-)


-- 

Thanks,

--Raman
♈ Id: kg:/m/0285kf1  🦮

**Comment by Boruch-Baum** [comment]
On 2021-01-25 19:59, T. V. Raman wrote:
>    :-) re screen flicker -- I cant see the screen at all, so it definitely
>    doesn't flicker for me;-)

I should have figured that out. Thick of me. Anyway, the fix for
keyboard-quit has been committed and pushed to github, but MELPA lags,
so it's still distributing my version from 01-21.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Pull request closed without merging**
