### PR TITLE
Replace '*' with 50ms of silence when processing 'tts_say' protocol m…

### PR DESCRIPTION
**Pull request by hellomatty**
…essages

### CODE REVIEW

**Comment by hellomatty** [comment]
The mac speech server seems to voice the '*' morpheme boundary marker - this patch looks a bit blunt but seems to squash it. 50ms seems to work but I picked the value a bit arbitrarily :-/

**Comment by tvraman** [comment]
Thanks for the patch -- will pull it in a few

**Comment by tvraman** [comment]
I've applied the patch. If someone knows what the Mac   engine
uses for a morpheme boundary, we should use that for better effect.
Also, the time value 50ms may need to be scaled by the speech-rate in effect  for maximal effectiveness.>>>>> "Matthew" == Matthew Wood <notifications@github.com> writes:
    Matthew> The mac speech server seems to voice the '*'
    Matthew> morpheme boundary marker - this patch looks a bit
    Matthew> blunt but seems to squash it. 50ms seems to work but
    Matthew> I picked the value a bit arbitrarily :-/ --- Reply
    Matthew> to this email directly or view it on GitHub:
    Matthew> https://github.com/tvraman/emacspeak/pull/10#issuecomment-145130963

**Comment by hellomatty** [comment]
tx for the merge - I'm proud to make even such a small contribution to an amazing project

Your comments are well made - this is really just a sticking plaster ;-)

On 3 Oct 2015, at 03:30, T. V. Raman <notifications@github.com<mailto:notifications@github.com>> wrote:

I've applied the patch. If someone knows what the Mac engine
uses for a morpheme boundary, we should use that for better effect.
Also, the time value 50ms may need to be scaled by the speech-rate in effect for maximal effectiveness.>>>>> "Matthew" == Matthew Wood <notifications@github.com<mailto:notifications@github.com>> writes:
Matthew> The mac speech server seems to voice the '*'
Matthew> morpheme boundary marker - this patch looks a bit
Matthew> blunt but seems to squash it. 50ms seems to work but
Matthew> I picked the value a bit arbitrarily :-/ --- Reply
Matthew> to this email directly or view it on GitHub:
Matthew> https://github.com/tvraman/emacspeak/pull/10#issuecomment-145130963

**Comment by tvraman** [comment]
I changed it to replace '[*]' rather than just '*' makes it a
little less oof a blunt hammer. Make sure it works.
>>>>> "Matthew" == Matthew Wood <notifications@github.com> writes:
    Matthew> tx for the merge - I'm proud to make even such a
    Matthew> small contribution to an amazing project Your
    Matthew> comments are well made - this is really just a
    Matthew> sticking plaster ;-)
    Matthew> 
    Matthew> On 3 Oct 2015, at 03:30, T. V. Raman
    Matthew> <notifications@github.com<mailto:notifications@github.com>>
    Matthew> wrote:
    Matthew> 
    Matthew> I've applied the patch. If someone knows what the
    Matthew> Mac engine uses for a morpheme boundary, we should
    Matthew> use that for better effect. Also, the time value
    Matthew> 50ms may need to be scaled by the speech-rate in
    Matthew> effect for maximal effectiveness.>>>>> "Matthew" ==
    Matthew> Matthew Wood
    Matthew> <notifications@github.com<mailto:notifications@github.com>>
    Matthew> writes: The mac speech server seems to voice the '*'
    Matthew> morpheme boundary marker - this patch looks a bit
    Matthew> blunt but seems to squash it. 50ms seems to work but
    Matthew> I picked the value a bit arbitrarily :-/ --- Reply
    Matthew> to this email directly or view it on GitHub:
    Matthew> https://github.com/tvraman/emacspeak/pull/10#issuecomment-145130963
    Matthew> 
    Matthew> — Reply to this email directly or view it on
    Matthew> GitHub<https://github.com/tvraman/emacspeak/pull/10#issuecomment-145194595>.
    Matthew> 
    Matthew> 
    Matthew> --- Reply to this email directly or view it on
    Matthew> GitHub:
    Matthew> https://github.com/tvraman/emacspeak/pull/10#issuecomment-145490362

**Comment by hellomatty** [comment]
Your less blunt hammer works for me.
I went back to the mac speech api docs but couldn't see a way to mark a morpheme boundary, but that could be my oversight :-(

**Comment by tvraman** [comment]
It's unfortunate that they dont expose that functionality via
inline markup; sadly I dont believe morpheme  boundaries even
made it into SSML. 
>>>>> "Matthew" == Matthew Wood <notifications@github.com> writes:
    Matthew> Your less blunt hammer works for me. I went back to
    Matthew> the mac speech api docs but couldn't see a way to
    Matthew> mark a morpheme boundary, but that could be my
    Matthew> oversight :-(
    Matthew> 
    Matthew> --- Reply to this email directly or view it on
    Matthew> GitHub:
    Matthew> https://github.com/tvraman/emacspeak/pull/10#issuecomment-148941491

**Pull request closed without merging**
